---
- name: Orchestrate the stacks
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - include_vars: roles/common/vars/main.yml

    - name: Orchestrate webservers with CloudFormation
      cloudformation:
        stack_name: "{{ app_name }}-web-{{ lookup('env', 'APPLICATION_ENV') }}"
        state: "present"
        region: "{{ aws_region }}"
        template: "roles/appserver/files/cloudformation.json"
        template_parameters:
          ELBName: "{{ app_name }}-elb-{{ lookup('env', 'APPLICATION_ENV') }}"
          KeyPair: "{{ lookup('env', 'AWS_KEY_PAIR') }}"

    - name: Orchestrate dbservers with CloudFormation
      cloudformation:
        stack_name: "{{ app_name }}-db-{{ lookup('env', 'APPLICATION_ENV') }}"
        state: "present"
        region: "{{ aws_region }}"
        template: "roles/dbserver/files/cloudformation.json"
        template_parameters:
          DbUsername: "{{ db_username }}"
          DbPassword: "{{ db_password }}"
