---
- name: Orchestration
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - include_vars: roles/common/vars/main.yml

    - name: Orchestrate webservers with CloudFormation
      cloudformation:
        stack_name: "{{ app_name }}-web-{{ lookup('env', 'APPLICATION_ENV') }}"
        state: "present"
        region: "{{ aws_region }}"
        template: "roles/appserver/files/cloudformation.json"
        template_parameters:
          VpcId: "vpc-774daf1e"
          ELBName: "{{ app_name }}-elb-{{ lookup('env', 'APPLICATION_ENV') }}"
          KeyPair: "{{ lookup('env', 'AWS_KEY_PAIR') }}"

    - name: Orchestrate dbservers with CloudFormation
      cloudformation:
        stack_name: "{{ app_name }}-db-{{ lookup('env', 'APPLICATION_ENV') }}"
        state: "present"
        region: "{{ aws_region }}"
        template: "roles/dbserver/files/cloudformation.json"
        template_parameters:
          VpcId: "vpc-774daf1e"
          DbUsername: "{{ db_username }}"
          DbPassword: "{{ db_password }}"
          Environment: "{{ lookup('env', 'APPLICATION_ENV') }}"

    - name: Orchestrate cacheservers with CloudFormation
      cloudformation:
        stack_name: "{{ app_name }}-cache-{{ lookup('env', 'APPLICATION_ENV') }}"
        state: "present"
        region: "{{ aws_region }}"
        template: "roles/cacheserver/files/cloudformation.json"
        template_parameters:
          VpcId: "vpc-774daf1e"
          Environment: "{{ lookup('env', 'APPLICATION_ENV') }}"
